### PR TITLE
query_balance test fixes

### LINKED ISSUE #78: Query function fixes

### PR DESCRIPTION
**Pull request by stormeye2000**

### CODE REVIEW

File: tests/steps/query_balance_test.go [hunk 1]
```diff
@@ -115,19 +118,60 @@ func InitializeQueryGetBalance(ctx *godog.ScenarioContext) {
...
+
+		receiverKey := utils.GetUserPublicKey(userId)
+
+		if err == nil {
+			publicKey := receiverKey
+			identifier := rpc.PurseIdentifier{
+				MainPurseUnderPublicKey: &publicKey,
+			}
+			initialBalanceResult, err = sdk.QueryBalance(context.Background(), identifier)
+		}
```
Comment (meywood) [inline tests/steps/query_balance_test.go:134]: Shoudn't we return the err here if not nill?

**Review by meywood — CHANGES_REQUESTED** [review]

**Review by meywood — APPROVED** [review]
